### ISSUE TITLE
years missing from by year charts (x -axis)

### ISSUE THREAD

**Issue by risserlin** [BaderLab/SocialNetworkApp#101]
![image](https://cloud.githubusercontent.com/assets/3842763/9501406/3ab07b2c-4bf9-11e5-9959-7369c823bd2a.png)

**Comment by kofiav** [comment]
Bug is already mentioned in #82 

I talked to the Cytoscape devs about it, and even sent a bug report but they haven't gotten back to me yet.

**Comment by risserlin** [comment]
Okay.

**Comment by kofiav** [comment]
Bug has been fixed in build bde0fde53cbbdcf9ab7e67aa4fb289deef0849e1
