### ISSUE TITLE
Allow user to specify threshold for number of authors per paper computed for

### ISSUE THREAD

**Issue by risserlin** [BaderLab/SocialNetworkApp#28]
Some papers can have more than 1000 authors which produces unmanageable cliques in the network. 

Allow the user to set a maximum number that it will compute for.  Output the articles excluded based on their thresholds and add an option for the user to select which of those articles they want to included/exclude.

**Comment by kofiav** [comment]
Is the app supposed to exclude the publication outright if it does not match the threshold or is it alright if it only includes the first X authors (where X is the threshold)? Currently the app supports the latter.

**Comment by risserlin** [comment]
You can give the choice to the user.Personally I would exclude the publication.  The threshold is pretty high even creating the edges for 1999 authors is expensive.
A few things you can do:
Create a log file to contain the citation for any publication that doesn't meet the threshold.
Maybe have an option to include the publication but only use authors that are already in the network.
