### ISSUE TITLE
Pubmed XML does not contain citation counts

### ISSUE THREAD

**Issue by risserlin** [BaderLab/SocialNetworkApp#29]
Contact ncbi to find out why?

Add inidvidual search for each pubmed in an xml file to get their counts.  Is this too expensive though for time to build?

**Comment by kofiav** [comment]
I just sent an email to NCBI. Another issue is that even though PubMed stores the institution affiliations of authors this data isn't present in the XML files obtained through eUtils. To include that data users have to go to PubMed, execute a search and export the results. This isn't ideal. It would help if NCBI made everything more consistent.

**Comment by risserlin** [comment]
did NCBI get back to you?

**Comment by kofiav** [comment]
Not yet. But in the meantime I have implemented your suggestion (doing an eUtils search for each publication and calculating citation counts in that way). Last time I checked it works, but it's definitely not a good long term solution.
