### ISSUE TITLE
pubmed query returns "Search did not yield any results" when there are results doing the same query in pubmed 

### ISSUE THREAD

**Issue by risserlin** [BaderLab/SocialNetworkApp#37]
Query fro the pubmed search bar is:
("Andrews B"[Author] OR  "Attisano L"[Author] OR  "Audet J"[Author] OR  "Bader G"[Author] OR  "Blencowe B"[Author] OR  "Boone C"[Author] OR  "Brown G"[Author] OR  "Caudy A"[Author] OR  "Chan W"[Author] OR  "Emili A"[Author] OR  "Fraser A"[Author] OR  "Frey B"[Author] OR  "Gilbert P"[Author] OR  "Greenblatt J"[Author] OR  "Hughes T"[Author] OR  "Kim P"[Author] OR  "van der Kooy D"[Author] OR  "Krause H"[Author] OR  "Moffat J"[Author] OR  "Morris Q"[Author] OR  "Morshead C"[Author] OR  "Rosebrock A"[Author] OR  "Roth F"[Author] OR  "Roy P"[Author] OR  Ryu WS"[Author] OR  "Sefton M"[Author] OR  "Shoichet M"[Author] OR  "Sidhu S"[Author] OR  "Stagljar I"[Author] OR  "Taipale M"[Author] OR  "Wheeler A"[Author] OR  "Yip C"[Author] OR  "Zandstra P"[Author] OR  "Zhang Z"[Author]) and toronto

Need a more descriptive error.  Is the query too long? unrecognized word?

**Comment by kofiav** [comment]
Two issues here:

(1) The query isn't entirely valid. There is a missing quotation mark. Ryu WS"[Author] should be "Ryu WS"[Author]

(2) The # of valid publications resulting from the (correct) query is greater than 500 (26924 to be exact) and the app basically doesn't generate a network out of it. I've modified this, but the app seems unable to generate the network regardless (still investigating). I seem to recall that NCBI doesn't really like it when users have extremely large requests (> 500). What was the story behind this?

**Comment by kofiav** [comment]
Update: Network loaded but it took a very long time. Probably a good idea to notify users that the request is really large and allow them to back out (if they wish).
