### ISSUE TITLE
PMIDs retrieved from eUtils are not consistent with PMIDs provided by PubMed xml

### ISSUE THREAD

**Issue by kofiav** [BaderLab/SocialNetworkApp#55]
Sometimes the PMIDs provided by PubMed xml exports are not consistent with what is provided by eUtils even though they obviously refer to the same record. For example, the PubMed xml output will state the PMID of a particular record is 892400 while eUtils will claim that the same record has a PMID of 8924. The app is currently ignoring publications which have inconsistencies of this type - a better solution should be implemented.

**Comment by gbader** [comment]
This sounds like a problem in the code processing eUtils results - is the number being converted from 892400 to 8924 in that code somehow?

**Comment by kofiav** [comment]
I believe so. The ids found in both the exported xml and the eUtils results are equivalent. Somehow the SAX parser is truncating a few of the IDs. It is similar to what is causing issue #42

**Comment by kofiav** [comment]
Fixed in c7e808d
