### ISSUE TITLE
user updatable institution to location associations

### ISSUE THREAD

**Issue by risserlin** [BaderLab/SocialNetworkApp#7]
Add the ability to update the static institution to location association file. 
For instance, currently Sick kids has no location specification.  Right click on author that has an unknown location and add an institution to the set of institution and define which location it should be associated with.  
User will then have the option to save this update locally or globally (i.e. save locally to session if it is a change you want only for the given session, save globally when the change is needed for any network created).

**Comment by kofiav** [comment]
Fixed
