### ISSUE TITLE
Orientation of charts

### ISSUE THREAD

**Issue by kofiav** [BaderLab/SocialNetworkApp#83]
It is currently not possible to specify the orientation of charts through code. This has to be fixed.

**Comment by risserlin** [comment]
is it not possible because the feature isn't there in the cytoscape api? or a different reason?  If something is missing from cytoscape api then report it as a bug/feature request at http://chianti.ucsd.edu/cyto_web/bugreport/bugreport.php

**Comment by kofiav** [comment]
Fixed in 67ef955a72b88468092b6c1caea944efca4c6b03
