### ISSUE TITLE
Create an additional attribute that stores the homepage of an author

### ISSUE THREAD

**Issue by kofiav** [BaderLab/SocialNetworkApp#88]
Requires some text mining (search author lastname + 'lab' since that seems to be the template), but if author homepages are easy to retrieve, we could have an extra attribute called 'Homepage' that stores the homepage of an individual author (N/A if the homepage could not be found).

**Comment by risserlin** [comment]
No need to add this to the app.  A user can simply load in the website through node table import.

**Comment by kofiav** [comment]
Sure, got you.
