### ISSUE TITLE
Add affiliation data to Scopus networks

### ISSUE THREAD

**Issue by kofiav** [BaderLab/SocialNetworkApp#97]
Scopus makes it possible to export all the information associated with a publication, including the affiliations of the co-authors. It would be beneficial if the app could read such files. The user guide will also have to be updated so that users know how to export all the data from Scopus.

**Comment by risserlin** [comment]
It should also be backwards compatible.  The app has been around for a while now and some people might be accustomed to using the basic csv downloaded fille to build their networks.  It should be easy to check which file they are using.
